### ISSUE TITLE
speed optimizations

### ISSUE THREAD

**Issue by paulchrisluke** [pcl-labs/we-are-mini-golf-frontend#207]
assets feel sluggish to load, try a loading spinner to cover

keep in mind assets should load by course selection, not every course at once

**Comment by paulchrisluke** [comment]
this is being worked on to move stuff to local storage, but we may still want to add spinners https://github.com/whynotearth/we-are-mini-golf-frontend/pull/219

**Comment by freedannyv** [comment]
Done and done. Please check staging
