### ISSUE TITLE
Further speed optimizations. 

### ISSUE THREAD

**Issue by paulchrisluke** [pcl-labs/we-are-mini-golf-frontend#245]
currently, the site is at an acceptable 72/100 speed index. Currently using lazy loading and pre-fetching, but there could be further optimizations made:

The following image's are above 200kb, and loading initiallly, some changes could occur:

- [ ] remove this image, I don't think we need it since the grid is shaped https://app.weareminigolf.com/img/course-grid-empty.d7f0ee44.jpg?__WB_REVISION__=d7f0ee44b2d69cafde6e0badeefc5746 

- [ ] this image is loaded twice, remove duplicate loading https://app.weareminigolf.com/img/score-input-screen.38023c3c.jpg?__WB_REVISION__=38023c3c3250d1de707f163c3e6d3c59

- [ ] optimize the following images to be smaller, and replace:

https://app.weareminigolf.com/img/final-ranking-screen.e66c1679.jpg?__WB_REVISION__=e66c1679d4c4c1497855d6c0042d638c

https://app.weareminigolf.com/img/score-input-screen.38023c3c.jpg?__WB_REVISION__=38023c3c3250d1de707f163c3e6d3c59

https://app.weareminigolf.com/img/loading-screen.c99370e5.jpg

https://app.weareminigolf.com/img/score-total-screen.895bf403.jpg?__WB_REVISION__=895bf40339f5041e381c45f4fd4ec371

https://app.weareminigolf.com/img/Confettis-gif.09808f53.gif?__WB_REVISION__=09808f53b42ba72c94c443e51940af31

https://app.weareminigolf.com/img/last-hole-screen.e92ad2a6.jpg?__WB_REVISION__=e92ad2a6baa7eea5077bbf32feebe3d2

**Comment by weareminigolf** [comment]
We have created smaller assets and saved a lot of space (-70% on assets) https://we.tl/t-eIRGJL5TXK

Do NOT remove the navigation PATH background. loading it piece by piece from strapi is creating the bigest delays AND is actually heavier. Strapi only has transparent assets that are SUPER light and load on top of the course.

**Comment by weareminigolf** [comment]
AND we reduced the GIF too.
![Confettis-gif](https://user-images.githubusercontent.com/76088063/113659757-030dbe00-96a3-11eb-9770-0c3b880a8286.gif)
